---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@1.3.8
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'linux-vm-example / Get min/max versions'
...
