name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  linux-vm-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.10
    with:
      working_directory: './_example/linux-vm/'

  windows-vm-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.10
    with:
      working_directory: './_example/windows-vm/'

